### PR TITLE
Fix: tasks/main.yml was pointing at a missing vars file

### PR DESCRIPTION
**Pull request by fosuoy**
Fix: tasks/main.yml was pointing at a missing vars file

Tested while imaging another laptop.

### CODE REVIEW

**Comment by pixie79** [comment]
No this breaks the system by removing the tasks for Ubuntu and Redhat - it has nothing to do with vars

**Comment by fosuoy** [comment]
You're right, apologies for that - that was lazy.

Selecting the correct tasks file is broken though, I think it will work if it takes the format:
- name: Include correct tasks
  include: "Debian.yml"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

As it stands now this is breaking the development_environment scripts - I'll make another pull request on Monday - apologies again for wasting your time with this one.

**Comment by pixie79** [comment]
You do not need to, this was fixed earlier in the week and merged correctly today

**Comment by fosuoy** [comment]
Right, I didn't realize - thanks for the reply.

**Pull request closed without merging**
